name: Deploy Angular App to Firebase Hosting on master

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Replace geminiApiKey in environment.ts
        run: |
          echo "const environment = require('./src/environments/environment');" > temp.js
          echo "environment.geminiApiKey = process.env.API_KEY_GEMINI;" >> temp.js
          node temp.js
        env:
          API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}

      - name: Build Angular project (production)
        run: npm run build -- --configuration=production

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0

        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: fitwise-app-77eaf
