name: Deploy Angular App (Experimental)

on:
  push:
    branches:
      - experiment/hypothesis

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project (production)
        run: npm run build -- --configuration=production

      - name: Deploy to Firebase Hosting (Experiment)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXPERIMENT }}"
          channelId: live
          projectId: fitwise-test
